const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

const GET_A_ORDER_REQUEST = "GET_A_ORDER_REQUEST";
const GET_A_ORDER_SUCCESS = "GET_A_ORDER_SUCCESS";
const GET_A_ORDER_FAIL = "GET_A_ORDER_FAIL";

const SELECT_CUSTOMER="SELECT_CUSTOMER";
const POST_A_ORDER_REQUEST = "POST_A_ORDER_REQUEST";
const POST_A_ORDER_SUCCESS = "POST_A_ORDER_SUCCESS";
const POST_A_ORDER_FAIL = "POST_A_ORDER_FAIL";

const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";
const CLEAR_ORDER = "CLEAR_ORDER";
export {
  GET_ORDERS_REQUEST,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAIL,
  GET_A_ORDER_REQUEST,
  GET_A_ORDER_SUCCESS,
  GET_A_ORDER_FAIL,
  POST_A_ORDER_FAIL,
  POST_A_ORDER_SUCCESS,
  POST_A_ORDER_REQUEST,
  ADD_ORDER_ITEM,
  REMOVE_ORDER_ITEM,
  CLEAR_ORDER,
  SELECT_CUSTOMER
};
