const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

const GET_A_ORDER_REQUEST = "GET_A_ORDER_REQUEST";
const GET_A_ORDER_SUCCESS = "GET_A_ORDER_SUCCESS";
const GET_A_ORDER_FAIL = "GET_A_ORDER_FAIL";
export {
  GET_ORDERS_REQUEST,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAIL,
  GET_A_ORDER_REQUEST,
  GET_A_ORDER_SUCCESS,
  GET_A_ORDER_FAIL,
};
