export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCSECSS = "GET_PRODUCTS_SUCCSESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_A_PRODUCT_REQUEST = "GET_A_PRODUCT_REQUEST";
export const GET_A_PRODUCT_SUCSECSS = "GET_A_PRODUCT_SUCSESS";
export const GET_A_PRODUCT_FAIL = "GET_A_PRODUCT_FAIL";
export const GET_A_PRODUCT_RESET = "GET_A_PRODUCT_RESET";

export const POST_A_PRODUCT_REQUEST = "POST_A_PRODUCT_REQUEST";
export const POST_A_PRODUCT_SUCSECSS = "POST_A_PRODUCT_SUCSESS";
export const POST_A_PRODUCT_FAIL = "POST_A_PRODUCT_FAIL";

export const EDIT_A_PRODUCT_REQUEST = "EDIT_A_PRODUCT_REQUEST";
export const EDIT_A_PRODUCT_SUCSECSS = "EDIT_A_PRODUCT_SUCSESS";
export const EDIT_A_PRODUCT_FAIL = "EDIT_A_PRODUCT_FAIL";
